org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=true
android.nonFinalResIds=false

systemProp.https.protocols=TLSv1.2,TLSv1.3

GROUP=com.github.violet000
VERSION_NAME=1.1.1
POM_URL=https://github.com/violet000/NewLandPlugins
